// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Coins struct {
	CoinID    uuid.UUID    `json:"coin_id"`
	Name      string       `json:"name"`
	Symbol    string       `json:"symbol"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Transactions struct {
	TransactionID uuid.UUID    `json:"transaction_id"`
	CoinID        uuid.UUID    `json:"coin_id"`
	Quantity      string       `json:"quantity"`
	PurchasePrice string       `json:"purchase_price"`
	PurchaseDate  time.Time    `json:"purchase_date"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
}
