// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateCoin(ctx context.Context, arg CreateCoinParams) (Coins, error)
	GetCoins(ctx context.Context, arg GetCoinsParams) ([]Coins, error)
}

var _ Querier = (*Queries)(nil)
